// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZ2DiAvU4gIyS0IsMgX4sLOx2UxuMvyM',
    appId: '1:11112963235:web:b9018a39ff8ee387057316',
    messagingSenderId: '11112963235',
    projectId: 'smart-bin-dcd7e',
    authDomain: 'smart-bin-dcd7e.firebaseapp.com',
    storageBucket: 'smart-bin-dcd7e.appspot.com',
    measurementId: 'G-35Z70RW50W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA3d2CHnC_BQ5rNrc9man2_t-QCKxpndQ',
    appId: '1:11112963235:android:b1aaab771ea36e7b057316',
    messagingSenderId: '11112963235',
    projectId: 'smart-bin-dcd7e',
    storageBucket: 'smart-bin-dcd7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzY3zb4QwOXH9z3xbLCcCnkDClwkiaz40',
    appId: '1:11112963235:ios:9f66d9bdebabc956057316',
    messagingSenderId: '11112963235',
    projectId: 'smart-bin-dcd7e',
    storageBucket: 'smart-bin-dcd7e.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzY3zb4QwOXH9z3xbLCcCnkDClwkiaz40',
    appId: '1:11112963235:ios:e2e3871ce5d6b894057316',
    messagingSenderId: '11112963235',
    projectId: 'smart-bin-dcd7e',
    storageBucket: 'smart-bin-dcd7e.appspot.com',
    iosBundleId: 'com.example.reviewApp',
  );
}
